[package]
name = "rest_client"
version = "0.1.0"
authors = ["Ian Costanzo <ian@anon-solutions.ca>"]

[dependencies]
native-tls = "0.1.4"
hyper = "0.11.9"
serde_json = "1.0"
reqwest = "0.8.5"
# reqwest = { git = "https://github.com/ianco/reqwest" }


