@startuml
node "TheOrgBook" {
[TheOrgBook Application]
}
database "TheOrgBook Wallet" {
[Identity 1]
[Identity n]
}
database "TOB Enterprise DB" {
folder "TOB Enterprise data" {
[TOB Data]
}
}
node "Government Entity" {
[Govt Application]
}
node "Indy Node" {
[Ledger]
[DID]
[Claim Schema]
[Claim Definition]
}
[TheOrgBook Application] --> [Govt Application]
[Govt Application] --> [TheOrgBook Application]
[TheOrgBook Application] --> [Identity 1]
[TheOrgBook Application] --> [Identity n]
[TheOrgBook Application] --> [TOB Data]
[TheOrgBook Application] --> [Ledger]
[Govt Application] --> [Ledger]
[Ledger] --> [DID]
[Ledger] --> [Claim Schema]
[Ledger] --> [Claim Definition]
@enduml
