@startuml
actor Client
participant Client order 10
participant TheOrgBook order 20
participant AnonCreds order 30
participant EnterpriseWallet order 50
database Wallet order 60
Client --> TheOrgBook: get_proof(subject_name, proof_req)
TheOrgBook --> AnonCreds: indy_prover_get_claims_for_proof_req(wallet, proof_req)
AnonCreds --> AnonCreds: extract_predicates()
AnonCreds --> EnterpriseWallet: get_claims(wallet, predicates)
EnterpriseWallet --> EnterpriseWallet: build_query_filter(predicates)
EnterpriseWallet --> Wallet: get_claims(filter)
EnterpriseWallet --> AnonCreds: claims
AnonCreds --> AnonCreds: build_proof(proof_req, claims)
AnonCreds --> TheOrgBook: proof
TheOrgBook --> Client: proof
@enduml
