@startuml
node "TOB" {
folder "TheOrgBook-Web" {
[TOB Web Application]
}
folder "TheOrgBook-API" {
[TOB API Application]
[VON Agent]
}
}
folder "Permitify" {
  [BC Registries]
  [Fraser Health Authority]
  [Ministry of Finance]
}
[BC Registries] .down.> [Fraser Health Authority]
[Fraser Health Authority] .down.> [Ministry of Finance]

[Data Loader] -left-> [BC Registries]
[Data Loader] -left-> [Fraser Health Authority]
[Data Loader] -left-> [Ministry of Finance]

[BC Registries] -left-> [TOB API Application]
[Fraser Health Authority] -left-> [TOB API Application]
[Ministry of Finance] -left-> [TOB API Application]

[TOB API Application] --> [VON Agent]
[TOB Web Application] -left-> [TOB API Application]

folder "Indy SDK" {
[Ledger API]
[Anoncreds API]
[Wallet API]
[Proxy Wallet]
}
component [Proxy Wallet] #Green
[VON Agent] --> [Ledger API]
[VON Agent] --> [Anoncreds API]
[VON Agent] --> [Wallet API]
[Anoncreds API] --> [Ledger API]
[Anoncreds API] --> [Wallet API]
[Wallet API] --> [Proxy Wallet]
node "Indy Node" {
[Ledger]
}
node "TOB Wallet API" {
[Remote Wallet]
}
component [Remote Wallet] #Green
database "TOB DB" {
folder "TOB Claims" {
[Claims]
}
folder "Remote Wallet DB" {
[Root Identity]
[Identity 1]
[Identity n]
}
}
[TOB Web Application] --> [Claims]
[TOB API Application] --> [Claims]
[Remote Wallet] --> [Root Identity]
[Remote Wallet] --> [Identity 1]
[Remote Wallet] --> [Identity n]
[Proxy Wallet] --> [Remote Wallet]
[Ledger API] --> [Ledger]
@enduml
